// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhimtBYTSSQRgewUd6L0JaK6W1tzp8nhM',
    appId: '1:234690204442:web:ecabd808dda36a9a9a12a3',
    messagingSenderId: '234690204442',
    projectId: 'mobileproject-b4648',
    authDomain: 'mobileproject-b4648.firebaseapp.com',
    storageBucket: 'mobileproject-b4648.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDw39Balw91YI69Ct6_CncUdDwYK_Dvbg',
    appId: '1:234690204442:android:a1a02033691d73b89a12a3',
    messagingSenderId: '234690204442',
    projectId: 'mobileproject-b4648',
    storageBucket: 'mobileproject-b4648.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ewTT_QPLS-6BSz1nhQmvX23vXzqUHCM',
    appId: '1:234690204442:ios:e403b401ad83c6459a12a3',
    messagingSenderId: '234690204442',
    projectId: 'mobileproject-b4648',
    storageBucket: 'mobileproject-b4648.appspot.com',
    iosBundleId: 'com.example.demoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ewTT_QPLS-6BSz1nhQmvX23vXzqUHCM',
    appId: '1:234690204442:ios:e403b401ad83c6459a12a3',
    messagingSenderId: '234690204442',
    projectId: 'mobileproject-b4648',
    storageBucket: 'mobileproject-b4648.appspot.com',
    iosBundleId: 'com.example.demoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhimtBYTSSQRgewUd6L0JaK6W1tzp8nhM',
    appId: '1:234690204442:web:850fc2ed646910769a12a3',
    messagingSenderId: '234690204442',
    projectId: 'mobileproject-b4648',
    authDomain: 'mobileproject-b4648.firebaseapp.com',
    storageBucket: 'mobileproject-b4648.appspot.com',
  );
}
