// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbxGq_iaPJQK6aeSGNaOR3cOXQBgJLr4',
    appId: '1:512914092191:web:c81d5f552d2ee6c96d72aa',
    messagingSenderId: '512914092191',
    projectId: 'project-c8cf6',
    authDomain: 'project-c8cf6.firebaseapp.com',
    storageBucket: 'project-c8cf6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ABdP4vb8vHe-IucPntipf9PczPpL6Rs',
    appId: '1:512914092191:android:0eb787750a35d7586d72aa',
    messagingSenderId: '512914092191',
    projectId: 'project-c8cf6',
    storageBucket: 'project-c8cf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fCCnPfddh5zGQkP_ubZk0ZPsKvE4PtE',
    appId: '1:512914092191:ios:91b7fccc928287a86d72aa',
    messagingSenderId: '512914092191',
    projectId: 'project-c8cf6',
    storageBucket: 'project-c8cf6.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fCCnPfddh5zGQkP_ubZk0ZPsKvE4PtE',
    appId: '1:512914092191:ios:91b7fccc928287a86d72aa',
    messagingSenderId: '512914092191',
    projectId: 'project-c8cf6',
    storageBucket: 'project-c8cf6.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsbxGq_iaPJQK6aeSGNaOR3cOXQBgJLr4',
    appId: '1:512914092191:web:b372f31c195388256d72aa',
    messagingSenderId: '512914092191',
    projectId: 'project-c8cf6',
    authDomain: 'project-c8cf6.firebaseapp.com',
    storageBucket: 'project-c8cf6.appspot.com',
  );
}
